Repository TeamNatron/ReleaseNotes-WebApp, pull requests merged in 2020-03, with the labels that each got.

#34 Improve release viewer styling AB#158
  src/components/releaseView/DenseReleaseNoteRow.jsx
  src/components/releaseView/FullReleaseNote.jsx
  src/components/releaseView/ReleaseView.jsx
  src/components/shared/ReleaseH1.jsx
  src/components/shared/ReleaseH2.jsx
Labels: enhancement

#33 Feature routing release
  src/components/Routes.jsx
  src/components/screen/ReleaseScreen.jsx
  src/components/screen/ReleasesScreen.jsx
Labels: helpful

#57 test that each screen renders
  src/components/Routes.jsx
  src/components/screen/AdminScreen.test.js
  src/components/screen/ArticleScreen.jsx
  src/components/screen/LandingScreen.test.js
  src/components/screen/LoginScreen.test.js
  src/components/screen/ReleaseEditorScreen.test.js
  src/components/screen/ReleaseEditorScreen.test.jsx
  src/components/screen/ReleaseNoteEditorScreen.test.js
  src/components/screen/ReleaseScreen.test.js
  src/components/screen/ReleasesScreen.test.js
  src/utils/test/testScreenConformance.js
Labels: helpful, testing

#61 Feature logout AB#163 AB#176
  src/App.js
  src/components/Navbar.jsx
  src/components/navbar/AccountMenu.jsx
  src/components/navbar/Navbar.jsx
  src/handlers/cookieHandler.js
  src/slices/authSlice.js
Labels: enhancement

#76 Feature/import release AB#240
  src/components/adminpanel/AzureDevOpsView.jsx
  src/components/screen/AdminScreen.jsx
  src/components/shared/AdminExpansionPanelBase.jsx
  src/slices/azureSlice.js
  src/slices/azureSlice.test.js
Labels: enhancement
