Repository TeamNatron/ReleaseNotes-WebApp, pull requests merged in 2020-04, with the labels that each got.

#78 Refactor products to toolkit conventions
  README.md
  src/actions/productActions.js
  src/actions/productActions.test.js
  src/components/adminpanel/AddProductForm.jsx
  src/components/screen/AdminScreen.jsx
  src/components/screen/LandingScreen.jsx
  src/reducers/combinedReducers.js
  src/reducers/productsReducer.js
  src/reducers/productsReducer.test.js
  src/slices/productsSlice.js
  src/slices/productsSlice.test.js
Labels: refactor

#87 Bugfix Import Azure Release AB#257
  src/components/adminpanel/AzureDevOpsView.jsx
  src/components/screen/AdminScreen.jsx
Labels: bug

#89 Bug/empty releasenotes previews
  src/components/shared/ReleaseNotePreview.jsx
  src/components/shared/ReleaseNotePreview.test.jsx
  src/utils/releaseNoteUtil.js
  src/utils/releaseNoteUtil.test.js
Labels: bug

#99 Mapping System Release Notes -> AzureDevOps Work items AB#289 AB#301
  src/components/adminpanel/AzureDevOpsView.jsx
  src/components/adminpanel/AzureMappingView.jsx
  src/reducers/combinedReducers.js
  src/slices/authSlice.js
  src/slices/azureSlice.js
  src/slices/mappingSlice.js
  src/slices/mappingSlice.test.js
  src/utils/azureUtils.js
Labels: enhancement
